_format_version: "3.0"
_transform: true

services:
  - name: start-page
    url: http://users-service:9065
    routes:
      - name: users
        paths:
          - /users

  - name: users-service
    url: http://users-service:9065
    routes:
      - name: get-user-by-id
        methods: [GET]
        paths:
          - ~/users/([a-f0-9\-]+)
        strip_path: false
        regex_priority: 1

      - name: update-user-by-id
        methods: [PUT]
        paths:
          - ~/users/([a-f0-9\-]+)
        strip_path: false
        regex_priority: 2

      - name: delete-user-by-id
        methods: [DELETE]
        paths:
          - ~/users/([a-f0-9\-]+)
        strip_path: false
        regex_priority: 2
