_format_version: "3.0"
_transform: true

services:
  - name: start-page
    url: http://users-service:9065
    routes:
      - name: users
        paths:
          - /users
        plugins:
          - name: jwt

  - name: users-service
    url: http://users-service:9065
    routes:
      - name: get-user-by-id
        methods: [GET]
        paths:
          - ~/users/([a-f0-9\-]+)
        strip_path: false
        regex_priority: 1

      - name: update-user-by-id
        methods: [PUT]
        paths:
          - ~/users/([a-f0-9\-]+)
        strip_path: false
        regex_priority: 2

      - name: delete-user-by-id
        methods: [DELETE]
        paths:
          - ~/users/([a-f0-9\-]+)
        strip_path: false
        regex_priority: 2

      - name: users-service-routes
        paths:
          - ~/users/oauth2/token
        strip_path: false
        methods:
          - GET
          - POST
        regex_priority: 10
        plugins:
          - name: oauth2
            config:
              enable_client_credentials: true
              enable_authorization_code: true
              scopes:
                - read
                - write
              provision_key: "some_provision_key"
              mandatory_scope: true

plugins:
      - name: jwt
        config:
          anonymous: <consumer_id>  # Если вы используете анонимного потребителя
          secret_is_base64: false  # Если ключ - это строка (не base64)
          claims_to_verify:  # Если нужно проверить какие-то claims
            - exp  # Пример: проверка срока действия токена
          run_on_preflight: true  # Обработка CORS запросов

      - name: file-log
        config:
          path: /tmp/kong-access.log