_format_version: "3.0"
_transform: true

oauth2_credentials:
  - name: my-app
    client_id: IBtQssyTj185ri5a5bESO4yjFqZYv3sG
    client_secret: knBsZsG19gXGAF1JKDrwXwa0AYydekCD
    redirect_uris:
      - http://localhost:3000/callback
    consumer: oauth2-client
    hash_secret: false
